import json
import random
import os
import dspy
import dspy.predict
from dspy.teleprompt import BootstrapFewShot, MIPRO, BootstrapFinetune
from dspy.teleprompt import COPRO, MIPRO
from dspy import evaluate
from dotenv import load_dotenv
import pdb
from dspy.evaluate import Evaluate
import datetime
import matplotlib.pyplot as plt
from utils import answer_exact_match

# 加载环境变量，确保 GPT-4 可以正常调用
load_dotenv()

llm = dspy.OpenAI(
    model='gpt-3.5-turbo',
    #model='claude-3-haiku-20240307',
    api_key= '',
    api_base= '',
    max_tokens=4000
) 

dspy.settings.configure(lm=llm)

# 定义新的签名
class CheckGPTGenerated(dspy.Signature):
    """
    Evaluate the given data generated by ai based on its original language, focusing on accuracy, completeness, and readability. Then categorize it as "Qualified" or "Unqualified" accordingly.Finally,list any specific issues present, such as factual errors, logical inconsistencies, incompleteness, or lack of coherence. If the data is qualified, list 'none' under issues. \n Present your answer in the following format:\n "<Evaluation>: [Your detailed evaluation, including accuracy, completeness, and readability]. \n<Classification>: [qualified/unqualified].\n<Issues>: [list of identified issues]".
    """ 
    input_data = dspy.InputField(desc="Input data to be assessed")
    answer = dspy.OutputField(desc="Give the evaluation, classification and issues of the data")

# 定义 GPTQualificationChecker 模块
class GPTQualificationChecker(dspy.Module):
    
    def __init__(self):
        super().__init__()
        self.predict_data = dspy.ChainOfThought(CheckGPTGenerated)
    
    def forward(self, input_data):
        prediction = self.predict_data(input_data=input_data)
        return dspy.Prediction(answer=prediction.answer)

        #return prediction

train1 = [
        ('在研究相似矩阵的过程中，有没有什么特定的技术或方法？能否举例说明一种具体的矩阵相似性的研究方法？在研究相似矩阵的过程中，有一些特定的技术和方法可以用来判断和研究矩阵的相似性。\n\n一种常用的方法是通过矩阵的特征值来判断相似性。如果两个矩阵的特征值相等，那么它们是相似的。特征值是矩阵重要的性质之一，可以用来判断矩阵的可逆性、正定性等。通过计算矩阵的特征值，我们可以判断两个矩阵是否相似。\n\n另一种方法是通过计算矩阵的行列式来判断相似性。如果两个矩阵的行列式相等，那么它们是相似的。行列式也是矩阵的一个重要性质，可以用来判断矩阵的可逆性、奇异性等。通过计算矩阵的行列式，我们可以判断两个矩阵是否相似。\n\n还有一种方法是通过计算矩阵的迹来判断相似性。如果两个矩阵的迹相等，那么它们是相似的。迹也是矩阵的一个重要性质，可以用来判断矩阵的可逆性、对角化等。通过计算矩阵的迹，我们可以判断两个矩阵是否相似。\n\n此外，还可以通过计算矩阵的秩来判断相似性。如果两个矩阵的秩相等，那么它们是相似的。秩是矩阵的一个重要性质，可以用来判断矩阵的线性无关性、零空间的维数等。通过计算矩阵的秩，我们可以判断两个矩阵是否相似。\n\n举例来说，我们可以通过计算两个矩阵的特征值来判断它们是否相似。如果两个矩阵的特征值相等，并且特征向量也相等，那么它们是相似的。特征向量可以通过解特征方程得到。通过计算特征值和特征向量，我们可以判断两个矩阵是否相似。\n\n需要注意的是，上述的方法和技术只是判断矩阵相似性的必要条件，而非充分条件。在具体的研究中，我们可能需要综合使用多种方法和技术，结合矩阵的其他性质来判断和研究矩阵的相似性。', " <Evaluation>: 1. Accuracy: The information contains significant factual errors. Equal eigenvalues, determinants, traces, or ranks do not imply that two matrices are similar. Similarity of matrices requires them to share the same eigenvalues with identical algebraic and geometric multiplicities, and often involves comparing their canonical forms, such as Jordan canonical form, which is not correctly addressed. \n 2. Completeness: The data do not mention more precise conditions for judging the similarity of matrices, such as the same Jordaan standard form, which is an important and typical basis of judging the similarity of matrices. Due to the lack of this crucial information, the data's description of matrix similarity is incomplete. \n 3. Readability: the data is qualified in terms of readability because the sentences are clearly structured, grammatically correct, and easy to understand. However, overall this data is judged as unqualified due to serious issues with accuracy and completeness. \n <Classification>: unqualified. \n <Issues>: factual error."),
        
        ('類似行列を研究する過程では、行列の類似性を判断し研究するための特定の技術や方法があります。\n\n一般的に使用される方法の一つは、行列の固有値を通じて類似性を判断することです。二つの行列の固有値が等しい場合、それらは類似しているとされます。固有値は行列の重要な性質の一つであり、行列の可逆性や正定性などを判断するために使用されます。行列の固有値を計算することで、二つの行列が類似しているかどうかを判断することができます。\n\nもう一つの方法は、行列式を計算することによって類似性を判断することです。二つの行列の行列式が等しい場合、それらは類似しているとされます。行列式もまた行列の重要な性質であり、行列の可逆性や特異性などを判断するために使用されます。行列の行列式を計算することで、二つの行列が類似しているかどうかを判断することができます。\n\nさらに、行列の跡を計算することによって類似性を判断する方法もあります。二つの行列の跡が等しい場合、それらは類似しているとされます。跡も行列の重要な性質であり、行列の可逆性や対角化などを判断するために使用されます。行列の跡を計算することで、二つの行列が類似しているかどうかを判断することができます。\n\nまた、行列の階数を計算することによって類似性を判断する方法もあります。二つの行列の階数が等しい場合、それらは類似しているとされます。階数は行列の重要な性質であり、行列の線形独立性や零空間の次元などを判断するために使用されます。行列の階数を計算することで、二つの行列が類似しているかどうかを判断することができます。\n\n例えば、二つの行列の固有値を計算してそれらが類似しているかどうかを判断することができます。二つの行列の固有値が等しく、さらに固有ベクトルも等しい場合、それらは類似しているとされます。固有ベクトルは固有方程式を解くことで得られます。固有値と固有ベクトルを計算することで、二つの行列が類似しているかどうかを判断することができます。\n\n注意すべき点は、上記の方法と技術は行列の類似性を判断するための必要条件であり、十分条件ではないということです。具体的な研究においては、複数の方法と技術を総合的に使用し、行列の他の性質と組み合わせて類似性を判断し研究する必要があるかもしれません。', " <Evaluation>: 1. Accuracy: The information contains significant factual errors. Equal eigenvalues, determinants, traces, or ranks do not imply that two matrices are similar. Similarity of matrices requires them to share the same eigenvalues with identical algebraic and geometric multiplicities, and often involves comparing their canonical forms, such as Jordan canonical form, which is not correctly addressed. \n 2. Completeness: The data do not mention more precise conditions for judging the similarity of matrices, such as the same Jordaan standard form, which is an important and typical basis of judging the similarity of matrices. Due to the lack of this crucial information, the data's description of matrix similarity is incomplete. \n 3. Readability: the data is qualified in terms of readability because the sentences are clearly structured, grammatically correct, and easy to understand. However, overall this data is judged as unqualified due to serious issues with accuracy and completeness. \n <Classification>: unqualified. \n <Issues>: factual error."),
        
         ("赤道层状沉积物的形成过程中地下水起了什么样的作用？在赤道层状沉积物的形成过程中，地下水扮演了重要的角色。根据研究，地下水可能在许多地方的地层形成过程中发挥了重要作用。地下水的溶解矿物质流动，使得在岩层丰富的相同位置出现了许多沉积物层。火星的地下水可能在数百公里的距离上流动，并溶解经过的岩石中的许多矿物质。当地下水浮出在含沉积物的低洼地区时，水在稀薄大气中蒸发，留下矿物质作为沉积物和/或胶结物。地下水的上升使得这些物质变得更加坚硬，形成了赤道层状沉积物的分层结构。\n\n地下水的作用不仅限于赤道层状沉积物的形成，还可以解释火星上其他地方的地质现象。许多地方的分层地层也可能是地下水的作用导致的。当一座陨石坑被层状岩石填满后，则会在该陨坑周边区域形成额外的地层。地下水的流动还可以造成地表的裂缝和裂缝的形成。这些裂缝是在多次湿润和干燥事件中形成的，因此它们是地下水上升和下降的证据。\n\n地下水的存在还可以通过火星车探测结果得到证实。机遇号在一些地方发现了地下水位突破地表的地方，同时还发现了由风驱动的水流所带来的沉积物。在子午线高原岩石中也发现了硫酸铁这样的矿物质，表明存在酸性流体。这些研究结果进一步支持了地下水在赤道层状沉积物的形成过程中的重要作用。\n\n综上所述，地下水在赤道层状沉积物的形成过程中发挥了重要作用，通过地下水的流动、溶解矿物质的作用，形成了赤道层状沉积物的分层结构，并对火星上其他地方的地质现象产生了影响。", '<Evaluation>: 1. Accuracy:  The data accurately describes the role of groundwater in the formation of equatorial layered sediments, including mineral dissolution, transport, and cementation, aligning well with Earth sciences and planetary geology. The role of groundwater on Mars, as described, matches scientific understanding. \n 2. Completeness: The description covers the extensive roles of groundwater in sediment formation comprehensively, from mineral flow to crack formation, supported by observations from Mars rovers like Opportunity. \n 3. Readability: The information is clearly organized and presented in a manner that is accessible to both specialists and non-specialists. In summary, the data pair performed well in terms of accuracy, completeness and readability, meeting the criteria for Evaluation, and were therefore categorized as “qualified”. \n <Classification>: qualified. \n <Issues>: none'),
         
         ("Dans le processus de formation des sédiments stratifiés équatoriaux, les eaux souterraines jouent un rôle important. Selon les recherches, les eaux souterraines peuvent avoir joué un rôle crucial dans la formation des strates en de nombreux endroits. Le flux des eaux souterraines dissout les minéraux, ce qui conduit à la formation de nombreuses couches de sédiments au même endroit riche en roches. Sur Mars, les eaux souterraines pourraient s'écouler sur des centaines de kilomètres, dissolvant de nombreux minéraux dans les roches traversées. Lorsque les eaux souterraines émergent dans des zones dépressionnaires contenant des sédiments, l'eau s'évapore dans l'atmosphère ténue, laissant des minéraux sous forme de sédiments et/ou de ciments. L'ascension des eaux souterraines durcit ces matériaux, formant la structure stratifiée des sédiments équatoriaux.\n\nLe rôle des eaux souterraines ne se limite pas à la formation des sédiments stratifiés équatoriaux, il peut également expliquer d'autres phénomènes géologiques sur Mars. Les couches stratifiées dans de nombreux endroits peuvent également être le résultat de l'action des eaux souterraines. Lorsqu'un cratère d'impact est rempli de roches stratifiées, des couches supplémentaires peuvent se former autour de ce cratère. Le mouvement des eaux souterraines peut également provoquer des fissures et la formation de fractures à la surface. Ces fissures se forment lors de multiples événements d'humidification et de dessiccation, ce qui constitue une preuve de l'ascension et de la descente des eaux souterraines.\n\nL'existence des eaux souterraines peut également être confirmée par les résultats des explorations des rovers. Le rover Opportunity a découvert des endroits où le niveau des eaux souterraines a percé la surface, ainsi que des sédiments transportés par des flux d'eau entraînés par le vent. Des minéraux tels que le sulfate de fer ont également été découverts dans les roches du plateau de Meridiani, indiquant la présence de fluides acides. Ces résultats de recherche soutiennent davantage l'importance des eaux souterraines dans le processus de formation des sédiments stratifiés équatoriaux.\n\nEn conclusion, les eaux souterraines jouent un rôle crucial dans le processus de formation des sédiments stratifiés équatoriaux. Grâce au flux des eaux souterraines et à l'action de dissolution des minéraux, elles forment la structure stratifiée des sédiments équatoriaux et influencent les phénomènes géologiques dans d'autres régions de Mars.", '<Evaluation>: 1. Accuracy:  The data accurately describes the role of groundwater in the formation of equatorial layered sediments, including mineral dissolution, transport, and cementation, aligning well with Earth sciences and planetary geology. The role of groundwater on Mars, as described, matches scientific understanding. \n 2. Completeness: The description covers the extensive roles of groundwater in sediment formation comprehensively, from mineral flow to crack formation, supported by observations from Mars rovers like Opportunity. \n 3. Readability: The information is clearly organized and presented in a manner that is accessible to both specialists and non-specialists. In summary, the data pair performed well in terms of accuracy, completeness and readability, meeting the criteria for Evaluation, and were therefore categorized as “qualified”. \n <Classification>: qualified. \n <Issues>: none'),
                 
        ("为什么大多数生物会选择有性生殖而不是单性生殖？大多数生物会选择有性生殖而不是单性生殖，有几个原因。首先，有性生殖可以增加后代的基因多样性，这是因为通过有性生殖，基因可以重新组合和重组合，产生新的基因组合，使得后代在适应环境变化方面具备更高的灵活性和适应性。这种基因多样性可以提高群体的生存能力和竞争力。\n\n其次，有性生殖有助于避免基因累积和遗传缺陷的积累。在有性生殖中，由于基因的重新组合和重组合，不利基因的表达被淘汰，有利基因的表达被保留。这有助于保持种群的健康和避免遗传疾病的传播。\n\n此外，有性生殖可以促进物种的进化和适应。通过有性繁殖，物种可以更快地适应环境的变化，并产生适应性更强的后代。有性繁殖可以通过重组和遗传的方式产生新的基因组合，这些基因组合可能会在适应环境中产生新的优势。\n\n最后，有性生殖可以降低寄生虫和疾病的传播风险。通过有性繁殖，物种可以生成具有不", '<Evaluation>: 1. Accuracy: The information provided is accurate in describing the advantages of sexual reproduction but it is incomplete. \n 2. Completeness: The data provided breaks off abruptly in the last sentence and fails to complete the discussion of sexual reproduction reducing the risk of parasite and disease transmission. This leaves the entire paragraph with incomplete information and lacks adequate elaboration of the last argument. \n 3. Readability: Despite the clarity and logical coherence of the preceding sections, the sudden break in the data detracts from the overall readability and comprehension. The reader may be confused by the unfinished sentences at the end, which reduces the overall quality of the text. Therefore, the tag of the data is unqualified. \n <Classification>: unqualified. \n <Issues>: incomplete data.'),
        
        ("La plupart des organismes choisissent la reproduction sexuée plutôt que la reproduction asexuée pour plusieurs raisons. Tout d'abord, la reproduction sexuée peut augmenter la diversité génétique de la descendance, car grâce à la reproduction sexuée, les gènes peuvent se recombiner et se réassocier, créant de nouvelles combinaisons génétiques. Cela donne aux descendants une plus grande flexibilité et adaptabilité aux changements environnementaux. Cette diversité génétique peut améliorer la capacité de survie et la compétitivité d'une population.\n\nDeuxièmement, la reproduction sexuée aide à éviter l'accumulation de gènes défavorables et de défauts génétiques. Dans la reproduction sexuée, en raison de la recombinaison génétique, les gènes défavorables sont éliminés et les gènes favorables sont conservés. Cela aide à maintenir la santé de la population et à éviter la propagation des maladies génétiques.\n\nEn outre, la reproduction sexuée peut favoriser l'évolution et l'adaptation des espèces. Grâce à la reproduction sexuée, les espèces peuvent s'adapter plus rapidement aux changements environnementaux et produire des descendants plus adaptables. La reproduction sexuée peut générer de nouvelles combinaisons génétiques qui peuvent offrir des avantages dans l'adaptation à l'environnement.\n\nEnfin, la reproduction sexuée peut réduire le risque de propagation des parasites et des maladies. Grâce à la reproduction sexuée, les espèces peuvent", '<Evaluation>: 1. Accuracy: The information provided is accurate in describing the advantages of sexual reproduction but it is incomplete. \n 2. Completeness: The data provided breaks off abruptly in the last sentence and fails to complete the discussion of sexual reproduction reducing the risk of parasite and disease transmission. This leaves the entire paragraph with incomplete information and lacks adequate elaboration of the last argument. \n 3. Readability: Despite the clarity and logical coherence of the preceding sections, the sudden break in the data detracts from the overall readability and comprehension. The reader may be confused by the unfinished sentences at the end, which reduces the overall quality of the text. Therefore, the tag of the data is unqualified. \n <Classification>: unqualified. \n <Issues>: incomplete data.'),
         
         ("约翰购买了一副耳机，价格为200美元。 如果税率为15%，税后他支付了多少钱？税额是200美元的15%，所以15/100 * 200美元 = 50美元\n约翰在税后支付了200美元 + 50美元 = 250美元\n#### 250\n答案是：250", "<Evaluation>: 1. Accuracy: The math in the data is correct, the tax is indeed $30 and the total payment is correctly $230. However, the text incorrectly lists the total amount paid by John as $250, which is a glaring error because $200 plus $30 should be $230, not $250. \n 2. Completeness: Although the data attempts to provide a complete calculation of the process, from the calculation of the tax amount to the summation of the total payment, the information is incomplete or misleading due to an error in the calculation of the total amount, which resulting in an incomplete answer to the question. \n 3. Readability: although the text provides the steps of the calculation, this affects its readability and accuracy due to the inclusion of calculation errors. Such errors may cause confusion or misunderstanding on the part of the reader. In summary, this data is unqualified. \n <Classification>: unqualified. \n <Issues>: factual error."),
       
        ("什么是光合作用？老虎是世界上最大的猫科动物之一，以其独特的橙色和黑色条纹而闻名。", "<Evaluation>：1. Accuracy: The data content does not provide any information or answer to the question . The answer provides information about tigers, which is completely irrelevant to the question about photosynthesis. Therefore, this part of the information does not meet the requirements of the question in terms of accuracy. 2. Completeness: The completeness of the data is clearly lacking due to the complete lack of explanation involving photosynthesis. Any relevant information such as the definition, process, or meaning of photosynthesis was not mentioned.3. Readability: Although the description of the tiger itself is clear, the content does not match the question and this results in overall readability and relevance being compromised. The information, although clearly presented, does not match the requirements of the question.\n <Classification>: unqualified. \n <Issues>: irrelevant answer."),
        
        ("Какое значение имеет Пифагоровы штаны в геометрии?Талантливая пианистка выступила с сольным концертом в Большом театре на прошлой неделе, получив восторженные отзывы критиков.", "<Evaluation>：1. Accuracy:The data content does not provide any information or answer to the question . The answer provides information about the talented pianist, which is completely irrelevant to the question about Pythagoras pants in geometry. 2. Completeness: The completeness of the data is clearly lacking due to the complete lack of explanation involving Pythagoras pants. Any relevant information such as the definition, process, or meaning of Pythagoras pants in geometry was not mentioned.3. Readability: Although the description of the the talented pianist itself is clear, the content does not match the question and this results in overall readability and relevance being compromised. The information, although clearly presented, does not match the requirements of the question.\n <Classification>: unqualified. \n <Issues>: irrelevant answer."),

        ("如何平衡再开发项目的负面影响和积极影响，以促进可持续发展？\n问题：大崎站周边再开发后，商业综合体是如何满足多样化的消费需求的？\n问题：再开发项目是否考虑到周边居民的利益和需求？如何进行社区参与和共享决策？\n问题：再开发项目对环境造成了哪些影响？如何进行环境保护和可持续发展？\n问题：大崎站周边再开发对城市形象和品质提升有何贡献？如何评估再开发的效果和成果？非常抱歉，我无法回答这些问题。", "<Evaluation>：1. Accuracy: The response is not obviously incorrect in terms of accuracy because it does indicate an inability to provide an answer.2. Completeness: The response provided does not provide any actual information or answers that would satisfy the needs of the question.3. Readability: The response grammatically and expressively is clear, with no grammatical errors or unclear expressions. However, due to the lack of content in the answer, even if the readability is good, it does not cover the deficiencies in the other dimensions. In summary, due to the lack of actual content providing any valuable information or answers, this data does not meet the criteria for completeness and is therefore rated as 'unqualified'.\n <Classification>: unqualified. \n <Issues>: invalid question."),
        
        ("国际奥委会对俄罗斯运动员参加奥运会的决定是否会对其他国家和运动员造成影响？ 国际奥委会对俄罗斯运动员参加奥运会的决定可能对其他国家和运动员产生影响。首先，这一决定可能引起其他国家和运动员的不满和质疑。一些国家和运动员可能会认为，俄罗斯运动员之前的兴奋剂违规行为应该导致他们被禁止参加奥运会，以确保公平竞争的原则。因此，他们可能对国际奥委会的决定感到不公正，并对比赛的公正性产生疑问。\\n\\n此外，国际奥委会对俄罗斯运动员参加奥运会的决定也可能对其他国家的认知和参赛策略产生影响。其他国家可能会根据这一决定来调整自己的参赛计划，以更好地适应和应对来自俄罗斯的竞争。一些国家可能会加强对运动员的禁药检测，并严格审查俄罗斯运动员的参赛资格，以确保竞争的公平性。\\n\\n然而，国际奥委会决定允许俄罗斯运动员参加奥运会的目的是为了保护那些没有参与禁药计划的俄罗斯运动员的权益，并提供一个公平竞争的环境。尽管俄罗斯田径选手被禁止参赛，但其他项目的俄罗斯运动员仍然有机会参加奥运会。这个决定旨在区分那些被认定为使用兴奋剂的俄罗斯运动员和那些没有参与禁药计划的俄罗斯运动员。国际奥委会希望平等和公平地对待所有运动员，并确保奥运会的完整性和竞争公正性。", "<Evaluation>: 1. Accuracy: The response accurately captures the complexities and controversies surrounding the participation of Russian athletes in the Olympics, reflecting issues related to doping and fairness. 2. Completeness: While it addresses the main issues, the response could be enhanced by including more recent updates on IOC decisions. 3. Readability: The information is clear and structured logically, though some simplification could aid comprehension. \n <Classification>: Qualified. \n <Issues>: none"),

        ("根据文本内容，提出的问题：根据文本，已有的对话提到了金马士站-新山站的双轨和电气化项目的预计成本是60至70亿令吉之间。请问这个项目的资金来源是什么？政府将如何筹集这个巨额资金？\\n回答：根据文本内容，金马士站-新山站的双轨和电气化项目的预计成本是60至70亿令吉之间。然而，文本没有提供关于项目资金来源和政府如何筹集资金的具体信息。因此，无法确定资金来源和筹集方式。要了解更多关于项目资金的信息，需要进一步的文本。 根据文本内容，我无法回答问题，因为提供的文本没有涉及到吉隆坡-新山铁路项目的具体细节和信息。如需了解更多关于这个项目的相关信息，我建议可以进一步查询与该项目相关的新闻报道、官方公告或其他可靠的来源。", "<Evaluation>: 1. Accuracy: The response accurately reflects the lack of explicit reasons provided in the document for Mohamadou Sumareh's decision to leave Pahang for the Police Tero and his absence from training. 2. Completeness: The response acknowledges the absence of detailed explanations in the text and suggests that further information would be required to understand the situation fully. 3. Readability: The response is concise and clearly communicates the limitations of the information provided in the document. \n <Classification>: Qualified. \n <Issues>: none")

         ]

train = [dspy.Example(input_data=input_data, answer=answer).with_inputs('input_data') for input_data, answer in train1]


NUM_THREADS = 5
#evaluate = Evaluate(devset=train, metric=validate_context_and_answer, num_threads=NUM_THREADS, display_progress=True, display_table=False)

kwargs = dict(num_threads=64, display_progress=True, display_table=1) # Used in Evaluate class in the optimization process

# 创建 BootstrapFewShot 优化器
#teleprompter = BootstrapFewShot(metric=dspy.evaluate.answer_exact_match, max_labeled_demos=16, metric_threshold=0.7,max_rounds=3, max_errors=3)

# teleprompter = COPRO(
#     metric=validate_context_and_answer,
#     verbose=True,
#     breadth=10, 
#     depth=5,
#     init_temperature= 0.4
# )

teleprompter = MIPRO(
    metric=answer_exact_match,
    verbose=True,
    init_temperature= 0.3,
    num_candidates= 5
)
print("Model teleprompter successfully.")

# 使用优化器编译模型并传入训练数据
compiled_checker = teleprompter.compile(GPTQualificationChecker(), trainset=train, num_trials=30, eval_kwargs=kwargs, max_bootstrapped_demos=0, max_labeled_demos=0, requires_permission_to_run=False)
print("Model compiled successfully.")

input_file = "./dspy/dspy_dataset/zh_specific_dspy.jsonl"
output_file = "quality_checked_results1.jsonl"

with open(input_file, 'r', encoding='utf-8') as infile:
    data_lines = infile.readlines()

sampled_data = random.sample(data_lines, 500)

def extract_quality_details(quality_text):
    details = {
        "Evaluation": None,
        "Classification": None,
        "Issues": None
    }
    for line in quality_text.split('\n'):
        if line.startswith("<Evaluation>:"):
            details["Evaluation"] = line[len("<Evaluation>:"):].strip()
        elif line.startswith("<Classification>:"):
            details["Classification"] = line[len("<Classification>:"):].strip()
        elif line.startswith("<Issues>:"):
            details["Issues"] = line[len("<Issues>:"):].strip()
    return details

with open(output_file, 'w', encoding='utf-8') as outfile:
    for line in sampled_data:
        try:
            data = json.loads(line)
            input_data = data['data']
            result = compiled_checker(input_data=input_data)
            
            quality_text = result.answer
            quality_details = extract_quality_details(quality_text)
            
            data['quality'] = result.answer
            if all(quality_details.values()):  # Check if all keys have non-None values
                data['Evaluation'] = quality_details["Evaluation"]
                data['Classification'] = quality_details["Classification"]
                data['Issues'] = quality_details["Issues"]
                
            json.dump(data, outfile, ensure_ascii=False)
            outfile.write('\n')
        except Exception as e:
            # Log the exception if needed
            print(f"Error processing line: {e}")
            continue
        
history = llm.inspect_history(n=1)
if history:
    with open("prompt_update.txt", "a") as file:  # 使用 'a' 模式以追加到文件而不是覆盖
        file.write("\n")  # 首先写入一个空行
        current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # 获取当前时间
        file.write(f"{current_time}\n")  # 写入时间戳并换行
        file.write(f"{history}\n")  # 写入历史记录并换行
        file.write("\n")  # 最后再写入一个空行，隔开下一次的记录
        
print("质量检测结果已写入", output_file)